apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: elk-project
      source:
        repoURL: 'https://github.com/rameshlinuxadmin/elk-stack.git'
        targetRevision: HEAD
        path: 'infrastructure/envoy-gateway'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
